[package]
name = "rusty_quant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4" 
statrs = "0.14.0"
nalgebra = "0.32"
